DROP TRIGGER IF EXISTS data_annotation_revisions_append_only ON data_annotation_revisions;
DROP FUNCTION IF EXISTS prevent_annotation_revision_mutation();
DROP TRIGGER IF EXISTS data_dataset_version_samples_mutable ON data_dataset_version_samples;
DROP FUNCTION IF EXISTS protect_dataset_version_samples();
DROP TRIGGER IF EXISTS data_dataset_versions_immutable ON data_dataset_versions;
DROP FUNCTION IF EXISTS protect_published_dataset_version();

DROP TABLE IF EXISTS data_migration_reports;
DROP TABLE IF EXISTS data_idempotency_records;
DROP TABLE IF EXISTS data_outbox_events;
DROP TABLE IF EXISTS data_audit_records;
DROP TABLE IF EXISTS data_dataset_access_grants;
DROP TABLE IF EXISTS data_export_jobs;
DROP TABLE IF EXISTS data_import_jobs;
DROP TABLE IF EXISTS data_hard_sample_imports;
DROP TABLE IF EXISTS data_lineage_snapshots;
DROP TABLE IF EXISTS data_lineage_edges;
DROP TABLE IF EXISTS data_quality_reports;
DROP TABLE IF EXISTS data_quality_issues;
DROP TABLE IF EXISTS data_quality_runs;
DROP TABLE IF EXISTS data_quality_rules;
DROP TABLE IF EXISTS data_annotation_reviews;
DROP TABLE IF EXISTS data_annotation_revisions;
DROP TABLE IF EXISTS data_annotations;
DROP TABLE IF EXISTS data_annotation_assignments;
DROP TABLE IF EXISTS data_annotation_tasks;
DROP TABLE IF EXISTS data_annotation_providers;
DROP TABLE IF EXISTS data_dataset_version_samples;
DROP TABLE IF EXISTS data_samples;
DROP TABLE IF EXISTS data_dataset_versions;
DROP TABLE IF EXISTS data_datasets;
